FROM jenkinsxio/builder-base:0.0.623

RUN yum -y groupinstall 'Development Tools'
RUN curl -f -o /etc/yum.repos.d/vbatts-bazel-epel-7.repo  https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo && \
  yum install -y bazel

ENV GOLANG_VERSION 1.11
RUN wget https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go$GOLANG_VERSION.linux-amd64.tar.gz && \
  rm go${GOLANG_VERSION}.linux-amd64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV PATH $PATH:/usr/local/
ENV GOROOT /usr/local/go
ENV GOPATH=/home/jenkins/go
ENV PATH $PATH:$GOPATH/bin

RUN go get github.com/gohugoio/hugo && \
  mv $GOPATH/bin/hugo /usr/local/ && \
  rm -rf $GOPATH/src/github.com/gohugoio
  
CMD ["go","version"]